### ISSUE TITLE
Not redistributable

### ISSUE THREAD

**Issue by pizzadude** [Wimpressive-Snaps/steamlink-snap#1]
I'm pretty sure SteamLink is not redistributable, and the only "allowed" place to host this is flathub.

"Steam Link is proprietary and not redistributable without permission. Valve representatives have already contacted the Flathub admins to arrange Flathub-specific permission to redistribute this."

Source: https://github.com/flathub/flathub/pull/2142

Did you get permission to put this on the snap store?

**Comment by AsciiWolf** [comment]
Yeah, @flexiondotorg should ideally contact Valve (@smcv / @TTimo) about this and make it an official Snap (since Flatpak support is pretty bad in Ubuntu).

**Comment by flexiondotorg** [comment]
I have written to Valve.

**Comment by flexiondotorg** [comment]
> Unfortunately, we aren't able to grant the permission you're requesting. If that changes in the future, we'll let you know.

The snap is now private and no longer available.
